name: rpo4
description: "Payment terminal for transport cards using NFC"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Network
  dio: ^5.4.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # File system & paths
  path_provider: ^2.1.1
  path: ^1.9.0
  
  # Logging
  logging: ^1.2.0
  
  # Running external processes (nfc utilities)
  process_run: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true